#!/bin/bash

IP=$(curl -sS ipv4.icanhazip.com)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)

# . Liner 
function baris_panjang() {
  echo -e " ———————————————————————————————————————"
}

until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${user_EXISTS} == '0' ]]; do
read -rp " Username         : " -e user
		user_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)

		if [[ ${user_EXISTS} == '1' ]]; then
      echo "Username: ${user}. sudah ada silahkan coba dengan username lain !!!"
      exit 1
		fi
	done

uuid=$(cat /proc/sys/kernel/random/uuid)
read -p " Limit User (GB) : " Quota
read -p " Limit User (IP) : " iplimit
read -p " Expired (days) : " masaaktif

tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
sed -i '/#trojanws$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#trojangrpc$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json

# Link Trojan Akun
systemctl restart xray
trojanlink1="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=bug.com#${user}"
trojanlink="trojan://${uuid}@bugkamu.com:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
trojanlink2="trojan://${uuid}@${domain}:80?path=%2Ftrojan-ws&security=none&host=${domain}&type=ws#${user}"

cat >/var/www/html/trojan-$user.txt <<-END
———————————————————————————————————————

# Format Trojan GO/WS

- name: Trojan-$user-GO/WS
  server: ${domain}
  port: 443
  type: trojan
  password: ${uuid}
  network: ws
  sni: ${domain}
  skip-cert-verify: true
  udp: true
  ws-opts:
    path: /trojan-ws
    headers:
        Host: ${domain}

# Format Trojan gRPC

- name: Trojan-$user-gRPC
  type: trojan
  server: ${domain}
  port: 443
  password: ${uuid}
  udp: true
  sni: ${domain}
  skip-cert-verify: true
  network: grpc
  grpc-opts:
    grpc-service-name: trojan-grpc
END

systemctl reload xray
systemctl reload nginx
service cron restart
trojanlink="trojan://${uuid}@${domain}:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
trojanlink1="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#${user}"
if [ ! -e /etc/trojan ]; then
  mkdir -p /etc/trojan
fi

if [[ -d /etc/kyt/limit/trojan ]]; then
echo -ne
else
mkdir -p /etc/kyt/limit/trojan/ip
fi
if [[ -z $iplimit ]]; then
echo -e "2" > /etc/kyt/limit/trojan/ip/$user
else
echo -e "$iplimit" > /etc/kyt/limit/trojan/ip/$user
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/trojan/${user}
fi
DATADB=$(cat /etc/trojan/.trojan.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/trojan/.trojan.db
fi
echo "### ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/trojan/.trojan.db

echo -e " TROJAN  "
echo
echo -e " Remarks      : ${user} " 
echo -e " Host/IP      : ${domain} "
echo -e " User Quota   : ${Quota} GB "
echo -e " User Ip      : ${iplimit} IP "
echo -e " Port NTLS    : 443-900 " 
echo -e " port WS      : 80,8880,8080 "
echo -e " Key          : ${uuid} "
echo -e " ISP          : $ISP "
echo -e " Path         : /trojan-ws " 
echo -e " ServiceName  : trojan-grpc "
baris_panjang
echo -e " Link WS : ${trojanlink} " 
baris_panjang
echo -e " Link TLS  : ${trojanlink2} " 
baris_panjang 
echo -e " Link GRPC : ${trojanlink1} " 
baris_panjang
echo -e " OpenClash : https://${domain}:81/trojan-$user.txt " 
baris_panjang
echo -e " Expiry in : $masaaktif Hari  "

rm -f $0
exit 0