#!/bin/bash

rm -f $0

function kill_ssh() {
    userdel -f ${user}
    rm -f /etc/ssh/${user}
    rm -f /etc/kyt/limit/ssh/ip/${user}
    rm -f /var/www/html/ssh-${user}
}

function kill_vmess() {
    exp=$(grep -wE "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    sed -i "/^### $user $exp/,/^},{/d" /etc/xray/config.json
    sed -i "/^### $user $exp/,/^},{/d" /etc/vmess/.vmess.db
    rm -f /etc/vmess/${user}
    rm -f /etc/kyt/limit/vmess/ip/${user}
}

function kill_trojan() {
    exp=$(grep -wE "^#! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    sed -i "/^#! $user $exp/,/^},{/d" /etc/xray/config.json
    sed -i "/### $user $exp/,/^},{/d" /etc/trojan/.trojan.db
    rm -f /etc/trojan/${user}
    rm -f /etc/kyt/limit/trojan/ip/${user}
}

if [[ $1 == "ssh" ]]; then
    user=${2}
    kill_ssh
    systemctl restart ws dropbear
    exit 0
elif [[ $1 == "vmess" ]]; then
    user=${2}
    kill_vmess
    systemctl restart xray
    exit 0
elif [[ $1 == "trojan" ]]; then
    user=${2}
    kill_trojan
    systemctl restart xray
    exit 0
else
    exit 0
fi